# -*- coding: utf-8 -*-
"""
Created on Tue Nov 10 16:18:49 2020

@author: bpe043
"""

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        
        MainWindow.setObjectName("MainWindow")
        #MainWindow.resize(1209, 902)
        MainWindow.setFixedSize(1680, 1050)
        
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        
        self.gridLayout_2.setObjectName("gridLayout_2")
        
        self.updateButtonWindow2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.updateButtonWindow2.setFont(font)
        self.updateButtonWindow2.setObjectName("updateButtonWindow2")
        self.gridLayout_2.addWidget(self.updateButtonWindow2, 0, 4, 1, 1)
        
        # TESTING
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.backButton.setFont(font)
        self.backButton.setObjectName("backButton")
        self.gridLayout_2.addWidget(self.backButton, 0, 3, 1, 1)
        
        
    
        
        self.gridLayoutWindow2 = QtWidgets.QGridLayout()
        self.gridLayoutWindow2.setObjectName("gridLayoutWindow2")
        
        # Labels
        self.labelWindow2 = QtWidgets.QLabel(self.centralwidget)
        self.labelWindow2.setScaledContents(True)
        self.labelWindow2.setObjectName("labelWindow2")
        self.gridLayoutWindow2.addWidget(self.labelWindow2, 4, 0, 1, 1)
        
        self.label_2Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2Window2.setScaledContents(True)
        self.label_2Window2.setObjectName("label_2Window2")
        self.gridLayoutWindow2.addWidget(self.label_2Window2, 6, 0, 1, 1)
        
        self.label_3Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_3Window2.setScaledContents(True)
        self.label_3Window2.setObjectName("label_3Window2")
        self.gridLayoutWindow2.addWidget(self.label_3Window2, 8, 0, 1, 1)
        
        self.label_4Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_4Window2.setScaledContents(True)
        self.label_4Window2.setObjectName("label_4Window2")
        self.gridLayoutWindow2.addWidget(self.label_4Window2, 10, 0, 1, 1)
        
        self.label_5Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_5Window2.setScaledContents(True)
        self.label_5Window2.setObjectName("label_5Window2")
        self.gridLayoutWindow2.addWidget(self.label_5Window2, 12, 0, 1, 1)
        
        self.label_6Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_6Window2.setScaledContents(True)
        self.label_6Window2.setObjectName("label_6Window2")
        self.gridLayoutWindow2.addWidget(self.label_6Window2, 14, 0, 1, 1)
        
        self.label_7Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_7Window2.setScaledContents(True)
        self.label_7Window2.setObjectName("label_7Window2")
        self.gridLayoutWindow2.addWidget(self.label_7Window2, 16, 0, 1, 1)
        
        self.label_8Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_8Window2.setScaledContents(True)
        self.label_8Window2.setObjectName("label_8Window2")
        self.gridLayoutWindow2.addWidget(self.label_8Window2, 18, 0, 1, 1)
        
        self.label_9Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_9Window2.setScaledContents(True)
        self.label_9Window2.setObjectName("label_9Window2")
        self.gridLayoutWindow2.addWidget(self.label_9Window2, 20, 0, 1, 1)
        
        self.label_10Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_10Window2.setScaledContents(True)
        self.label_10Window2.setObjectName("label_10Window2")
        self.gridLayoutWindow2.addWidget(self.label_10Window2, 22, 0, 1, 1)
        
        self.label_11Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_11Window2.setScaledContents(True)
        self.label_11Window2.setObjectName("label_11Window2")
        self.gridLayoutWindow2.addWidget(self.label_11Window2, 4, 1, 1, 1)
        
        self.label_12Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_12Window2.setScaledContents(True)
        self.label_12Window2.setObjectName("label_12Window2")
        self.gridLayoutWindow2.addWidget(self.label_12Window2, 6, 1, 1, 1)
        
        self.label_13Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_13Window2.setScaledContents(True)
        self.label_13Window2.setObjectName("label_13Window2")
        self.gridLayoutWindow2.addWidget(self.label_13Window2, 8, 1, 1, 1)
        
        self.label_14Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_14Window2.setScaledContents(True)
        self.label_14Window2.setObjectName("label_14Window2")
        self.gridLayoutWindow2.addWidget(self.label_14Window2, 10, 1, 1, 1)
        
        self.label_15Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_15Window2.setScaledContents(True)
        self.label_15Window2.setObjectName("label_15Window2")
        self.gridLayoutWindow2.addWidget(self.label_15Window2, 12, 1, 1, 1)
        
        self.label_16Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_16Window2.setScaledContents(True)
        self.label_16Window2.setObjectName("label_16Window2")
        self.gridLayoutWindow2.addWidget(self.label_16Window2, 14, 1, 1, 1)
        
        self.label_17Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_17Window2.setScaledContents(True)
        self.label_17Window2.setObjectName("label_17Window2")
        self.gridLayoutWindow2.addWidget(self.label_17Window2, 16, 1, 1, 1)
        
        self.label_18Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_18Window2.setScaledContents(True)
        self.label_18Window2.setObjectName("label_18Window2")
        self.gridLayoutWindow2.addWidget(self.label_18Window2, 18, 1, 1, 1)
        
        self.label_19Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_19Window2.setScaledContents(True)
        self.label_19Window2.setObjectName("label_19Window2")
        self.gridLayoutWindow2.addWidget(self.label_19Window2, 20, 1, 1, 1)
        
        self.label_20Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_20Window2.setScaledContents(True)
        self.label_20Window2.setObjectName("label_20Window2")
        self.gridLayoutWindow2.addWidget(self.label_20Window2, 22, 1, 1, 1)
        
        self.label_21Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_21Window2.setScaledContents(True)
        self.label_21Window2.setObjectName("label_21Window2")
        self.gridLayoutWindow2.addWidget(self.label_21Window2, 4, 2, 1, 1)
        
        self.label_22Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_22Window2.setScaledContents(True)
        self.label_22Window2.setObjectName("label_22Window2")
        self.gridLayoutWindow2.addWidget(self.label_22Window2, 6, 2, 1, 1)
    
        self.label_23Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_23Window2.setScaledContents(True)
        self.label_23Window2.setObjectName("label_23Window2")
        self.gridLayoutWindow2.addWidget(self.label_23Window2, 8, 2, 1, 1)
        
        self.label_24Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_24Window2.setScaledContents(True)
        self.label_24Window2.setObjectName("label_24Window2")
        self.gridLayoutWindow2.addWidget(self.label_24Window2, 10, 2, 1, 1)
        
        self.label_25Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_25Window2.setScaledContents(True)
        self.label_25Window2.setObjectName("label_25Window2")
        self.gridLayoutWindow2.addWidget(self.label_25Window2, 12, 2, 1, 1)
        
        self.label_26Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_26Window2.setScaledContents(True)
        self.label_26Window2.setObjectName("label_26Window2")
        self.gridLayoutWindow2.addWidget(self.label_26Window2, 14, 2, 1, 1)
        
        self.label_27Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_27Window2.setScaledContents(True)
        self.label_27Window2.setObjectName("label_27Window2")
        self.gridLayoutWindow2.addWidget(self.label_27Window2, 16, 2, 1, 1)
        
        self.label_28Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_28Window2.setScaledContents(True)
        self.label_28Window2.setObjectName("label_28Window2")
        self.gridLayoutWindow2.addWidget(self.label_28Window2, 18, 2, 1, 1)
        
        self.label_29Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_29Window2.setScaledContents(True)
        self.label_29Window2.setObjectName("label_29Window2")
        self.gridLayoutWindow2.addWidget(self.label_29Window2, 20, 2, 1, 1)
        
        self.label_30Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_30Window2.setScaledContents(True)
        self.label_30Window2.setObjectName("label_30Window2")
        self.gridLayoutWindow2.addWidget(self.label_30Window2, 22, 2, 1, 1)
        
        self.label_31Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_31Window2.setScaledContents(True)
        self.label_31Window2.setObjectName("label_31Window2")
        self.gridLayoutWindow2.addWidget(self.label_31Window2, 4, 3, 1, 1)
        
        self.label_32Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_32Window2.setScaledContents(True)
        self.label_32Window2.setObjectName("label_32Window2")
        self.gridLayoutWindow2.addWidget(self.label_32Window2, 6, 3, 1, 1)
        
        self.label_33Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_33Window2.setScaledContents(True)
        self.label_33Window2.setObjectName("label_33Window2")
        self.gridLayoutWindow2.addWidget(self.label_33Window2, 8, 3, 1, 1)
        
        self.label_34Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_34Window2.setScaledContents(True)
        self.label_34Window2.setObjectName("label_34Window2")
        self.gridLayoutWindow2.addWidget(self.label_34Window2, 10, 3, 1, 1)
        
        self.label_35Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_35Window2.setScaledContents(True)
        self.label_35Window2.setObjectName("label_35Window2")
        self.gridLayoutWindow2.addWidget(self.label_35Window2, 12, 3, 1, 1)
        
        self.label_36Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_36Window2.setScaledContents(True)
        self.label_36Window2.setObjectName("label_36Window2")
        self.gridLayoutWindow2.addWidget(self.label_36Window2, 14, 3, 1, 1)
        
        self.label_37Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_37Window2.setScaledContents(True)
        self.label_37Window2.setObjectName("label_37Window2")
        self.gridLayoutWindow2.addWidget(self.label_37Window2, 16, 3, 1, 1)
    
        self.label_38Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_38Window2.setScaledContents(True)
        self.label_38Window2.setObjectName("label_38Window2")
        self.gridLayoutWindow2.addWidget(self.label_38Window2, 18, 3, 1, 1)
        
        self.label_39Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_39Window2.setScaledContents(True)
        self.label_39Window2.setObjectName("label_39Window2")
        self.gridLayoutWindow2.addWidget(self.label_39Window2, 20, 3, 1, 1)
    
        self.label_40Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_40Window2.setScaledContents(True)
        self.label_40Window2.setObjectName("label_40Window2")
        self.gridLayoutWindow2.addWidget(self.label_40Window2, 22, 3, 1, 1)
        
        self.label_41Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_41Window2.setScaledContents(True)
        self.label_41Window2.setObjectName("label_41Window2")
        self.gridLayoutWindow2.addWidget(self.label_41Window2, 4, 4, 1, 1)
        
        self.label_42Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_42Window2.setScaledContents(True)
        self.label_42Window2.setObjectName("label_42Window2")
        self.gridLayoutWindow2.addWidget(self.label_42Window2, 6, 4, 1, 1)
        
        self.label_43Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_43Window2.setScaledContents(True)
        self.label_43Window2.setObjectName("label_43Window2")
        self.gridLayoutWindow2.addWidget(self.label_43Window2, 8, 4, 1, 1)
        
        self.label_44Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_44Window2.setScaledContents(True)
        self.label_44Window2.setObjectName("label_44Window2")
        self.gridLayoutWindow2.addWidget(self.label_44Window2, 10, 4, 1, 1)
        
        self.label_45Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_45Window2.setScaledContents(True)
        self.label_45Window2.setObjectName("label_45Window2")
        self.gridLayoutWindow2.addWidget(self.label_45Window2, 12, 4, 1, 1)
        
        self.label_46Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_46Window2.setScaledContents(True)
        self.label_46Window2.setObjectName("label_46Window2")
        self.gridLayoutWindow2.addWidget(self.label_46Window2, 14, 4, 1, 1)
        
        self.label_47Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_47Window2.setScaledContents(True)
        self.label_47Window2.setObjectName("label_47Window2")
        self.gridLayoutWindow2.addWidget(self.label_47Window2, 16, 4, 1, 1)
        
        self.label_48Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_48Window2.setScaledContents(True)
        self.label_48Window2.setObjectName("label_48Window2")
        self.gridLayoutWindow2.addWidget(self.label_48Window2, 18, 4, 1, 1)
        
        self.label_49Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_49Window2.setScaledContents(True)
        self.label_49Window2.setObjectName("label_49Window2")
        self.gridLayoutWindow2.addWidget(self.label_49Window2, 20, 4, 1, 1)
        
        self.label_50Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_50Window2.setScaledContents(True)
        self.label_50Window2.setObjectName("label_50Window2")
        self.gridLayoutWindow2.addWidget(self.label_50Window2, 22, 4, 1, 1)
        
        self.label_51Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_51Window2.setScaledContents(True)
        self.label_51Window2.setObjectName("label_51Window2")
        self.gridLayoutWindow2.addWidget(self.label_51Window2, 4, 5, 1, 1)
        
        self.label_52Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_52Window2.setScaledContents(True)
        self.label_52Window2.setObjectName("label_52Window2")
        self.gridLayoutWindow2.addWidget(self.label_52Window2, 6, 5, 1, 1)
        
        self.label_53Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_53Window2.setScaledContents(True)
        self.label_53Window2.setObjectName("label_53Window2")
        self.gridLayoutWindow2.addWidget(self.label_53Window2, 8, 5, 1, 1)
       
        self.label_54Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_54Window2.setScaledContents(True)
        self.label_54Window2.setObjectName("label_54Window2")
        self.gridLayoutWindow2.addWidget(self.label_54Window2, 10, 5, 1, 1)

        self.label_55Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_55Window2.setScaledContents(True)
        self.label_55Window2.setObjectName("label_55Window2")
        self.gridLayoutWindow2.addWidget(self.label_55Window2, 12, 5, 1, 1)
        
        self.label_56Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_56Window2.setScaledContents(True)
        self.label_56Window2.setObjectName("label_56Window2")
        self.gridLayoutWindow2.addWidget(self.label_56Window2, 14, 5, 1, 1)
        
        self.label_57Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_57Window2.setScaledContents(True)
        self.label_57Window2.setObjectName("label_57Window2")
        self.gridLayoutWindow2.addWidget(self.label_57Window2, 16, 5, 1, 1)
        
        self.label_58Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_58Window2.setScaledContents(True)
        self.label_58Window2.setObjectName("label_58Window2")
        self.gridLayoutWindow2.addWidget(self.label_58Window2, 18, 5, 1, 1)
        
        self.label_59Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_59Window2.setScaledContents(True)
        self.label_59Window2.setObjectName("label_59Window2")
        self.gridLayoutWindow2.addWidget(self.label_59Window2, 20, 5, 1, 1)
        
        self.label_60Window2 = QtWidgets.QLabel(self.centralwidget)
        self.label_60Window2.setScaledContents(True)
        self.label_60Window2.setObjectName("label_60Window2")
        self.gridLayoutWindow2.addWidget(self.label_60Window2, 22, 5, 1, 1)
        
        
        self.fasitLabelWindow2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.fasitLabelWindow2.setFont(font)
        self.fasitLabelWindow2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fasitLabelWindow2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fasitLabelWindow2.setTextFormat(QtCore.Qt.RichText)
        self.fasitLabelWindow2.setScaledContents(False)
        self.fasitLabelWindow2.setAlignment(QtCore.Qt.AlignCenter)
        self.fasitLabelWindow2.setObjectName("fasitLabelWindow2")
        self.gridLayout_2.addWidget(self.fasitLabelWindow2, 0, 2, 1, 1)
        
        
        self.labelPagesDone = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.labelPagesDone.setFont(font)
        self.labelPagesDone.setFont(font)
        self.labelPagesDone.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelPagesDone.setTextFormat(QtCore.Qt.RichText)
        self.labelPagesDone.setScaledContents(False)
        self.labelPagesDone.setObjectName("labelPagesDone")
        self.gridLayout_2.addWidget(self.labelPagesDone, 0, 0, 1, 1)
        
        
        # Line edits
        
        self.lineEditWindow2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditWindow2.sizePolicy().hasHeightForWidth())
        self.lineEditWindow2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEditWindow2.setObjectName("lineEditWindow2")
        self.gridLayoutWindow2.addWidget(self.lineEditWindow2, 5, 0, 1, 1)
        
        self.lineEdit_2Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_2Window2.setObjectName("lineEdit_2Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_2Window2, 7, 0, 1, 1)
        
        self.lineEdit_3Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_3Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_3Window2.setObjectName("lineEdit_3Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_3Window2, 9, 0, 1, 1)
        
        self.lineEdit_4Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_4Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_4Window2.setObjectName("lineEdit_4Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_4Window2, 11, 0, 1, 1)
        
        self.lineEdit_5Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_5Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_5Window2.setObjectName("lineEdit_5Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_5Window2, 13, 0, 1, 1)
        
        self.lineEdit_6Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_6Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_6Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_6Window2.setObjectName("lineEdit_6Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_6Window2, 15, 0, 1, 1)
        
        self.lineEdit_7Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_7Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_7Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_7Window2.setObjectName("lineEdit_7Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_7Window2, 17, 0, 1, 1)
        
        self.lineEdit_8Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_8Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_8Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_8Window2.setObjectName("lineEdit_8Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_8Window2, 19, 0, 1, 1)
    
        self.lineEdit_9Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_9Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_9Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_9Window2.setObjectName("lineEdit_9Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_9Window2, 21, 0, 1, 1)
        
        self.lineEdit_10Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_10Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_10Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_10Window2.setObjectName("lineEdit_10Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_10Window2, 23, 0, 1, 1)
        
        self.lineEdit_11Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_11Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_11Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_11Window2.setObjectName("lineEdit_11Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_11Window2, 5, 1, 1, 1)
        
        self.lineEdit_12Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_12Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_12Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_12Window2.setObjectName("lineEdit_12Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_12Window2, 7, 1, 1, 1)
        
        self.lineEdit_13Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_13Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_13Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_13Window2.setObjectName("lineEdit_13Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_13Window2, 9, 1, 1, 1)
        
        self.lineEdit_14Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_14Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_14Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_14Window2.setObjectName("lineEdit_14Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_14Window2, 11, 1, 1, 1)
        
        self.lineEdit_15Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_15Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_15Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_15Window2.setObjectName("lineEdit_15Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_15Window2, 13, 1, 1, 1)
        
        self.lineEdit_16Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_16Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_16Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_16Window2.setObjectName("lineEdit_16Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_16Window2, 15, 1, 1, 1)
        
        self.lineEdit_17Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_17Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_17Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_17Window2.setObjectName("lineEdit_17Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_17Window2, 17, 1, 1, 1)
        
        self.lineEdit_18Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_18Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_18Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_18Window2.setObjectName("lineEdit_18Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_18Window2, 19, 1, 1, 1)
        
        self.lineEdit_19Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_19Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_19Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_19Window2.setObjectName("lineEdit_19Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_19Window2, 21, 1, 1, 1)
        
        self.lineEdit_20Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_20Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_20Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_20Window2.setObjectName("lineEdit_20Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_20Window2, 23, 1, 1, 1)
        
        self.lineEdit_21Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_21Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_21Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_21Window2.setObjectName("lineEdit_21Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_21Window2, 5, 2, 1, 1)
        
        self.lineEdit_22Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_22Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_22Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_22Window2.setObjectName("lineEdit_22Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_22Window2, 7, 2, 1, 1)
        
        self.lineEdit_23Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_23Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_23Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_23Window2.setObjectName("lineEdit_23Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_23Window2, 9, 2, 1, 1)
        
        self.lineEdit_24Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_24Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_24Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_24Window2.setObjectName("lineEdit_24Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_24Window2, 11, 2, 1, 1)
        
        self.lineEdit_25Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_25Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_25Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_25Window2.setObjectName("lineEdit_25Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_25Window2, 13, 2, 1, 1)
        
        self.lineEdit_26Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_26Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_26Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_26Window2.setObjectName("lineEdit_26Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_26Window2, 15, 2, 1, 1)
        
        self.lineEdit_27Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_27Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_27Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_27Window2.setObjectName("lineEdit_27Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_27Window2, 17, 2, 1, 1)
        
        self.lineEdit_28Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_28Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_28Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_28Window2.setObjectName("lineEdit_28Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_28Window2, 19, 2, 1, 1)
        
        self.lineEdit_29Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_29Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_29Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_29Window2.setObjectName("lineEdit_29Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_29Window2, 21, 2, 1, 1)
        
        self.lineEdit_30Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_30Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_30Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_30Window2.setObjectName("lineEdit_30Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_30Window2, 23, 2, 1, 1)
        
        self.lineEdit_31Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_31Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_31Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_31Window2.setObjectName("lineEdit_31Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_31Window2, 5, 3, 1, 1)
        
        self.lineEdit_32Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_32Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_32Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_32Window2.setObjectName("lineEdit_32Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_32Window2, 7, 3, 1, 1)
        
        self.lineEdit_33Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_33Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_33Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_33Window2.setObjectName("lineEdit_33Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_33Window2, 9, 3, 1, 1)
        
        self.lineEdit_34Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_34Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_34Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_34Window2.setObjectName("lineEdit_34Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_34Window2, 11, 3, 1, 1)
        
        self.lineEdit_35Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_35Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_35Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_35Window2.setObjectName("lineEdit_35Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_35Window2, 13, 3, 1, 1)
        
        self.lineEdit_36Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_36Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_36Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_36Window2.setObjectName("lineEdit_36Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_36Window2, 15, 3, 1, 1)
        
        self.lineEdit_37Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_37Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_37Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_37Window2.setObjectName("lineEdit_37Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_37Window2, 17, 3, 1, 1)
        
        self.lineEdit_38Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_38Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_38Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_38Window2.setObjectName("lineEdit_38Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_38Window2, 19, 3, 1, 1)
        
        self.lineEdit_39Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_39Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_39Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_39Window2.setObjectName("lineEdit_39Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_39Window2, 21, 3, 1, 1)
        
        self.lineEdit_40Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_40Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_40Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_40Window2.setObjectName("lineEdit_40Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_40Window2, 23, 3, 1, 1)
        
        self.lineEdit_41Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_41Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_41Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_41Window2.setObjectName("lineEdit_41Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_41Window2, 5, 4, 1, 1)
        
        self.lineEdit_42Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_42Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_42Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_42Window2.setObjectName("lineEdit_42Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_42Window2, 7, 4, 1, 1)
        
        self.lineEdit_43Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_43Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_43Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_43Window2.setObjectName("lineEdit_43Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_43Window2, 9, 4, 1, 1)
        
        self.lineEdit_44Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_44Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_44Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_44Window2.setObjectName("lineEdit_44Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_44Window2, 11, 4, 1, 1)
        
        self.lineEdit_45Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_45Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_45Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_45Window2.setObjectName("lineEdit_45Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_45Window2, 13, 4, 1, 1)
        
        self.lineEdit_46Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_46Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_46Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_46Window2.setObjectName("lineEdit_46Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_46Window2, 15, 4, 1, 1)
        
        self.lineEdit_47Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_47Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_47Window2.setMaximumSize(QtCore.QSize(250, 16777215)) 
        self.lineEdit_47Window2.setObjectName("lineEdit_47Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_47Window2, 17, 4, 1, 1)
        
        self.lineEdit_48Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_48Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_48Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_48Window2.setObjectName("lineEdit_48Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_48Window2, 19, 4, 1, 1)
        
        self.lineEdit_49Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_49Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_49Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_49Window2.setObjectName("lineEdit_49Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_49Window2, 21, 4, 1, 1)
        
        self.lineEdit_50Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_50Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_50Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_50Window2.setObjectName("lineEdit_50Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_50Window2, 23, 4, 1, 1)
        
        self.lineEdit_51Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_51Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_51Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_51Window2.setObjectName("lineEdit_51Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_51Window2, 5, 5, 1, 1)
        
        self.lineEdit_52Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_52Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_52Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_52Window2.setObjectName("lineEdit_52Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_52Window2, 7, 5, 1, 1)
        
        self.lineEdit_53Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_53Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_53Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_53Window2.setObjectName("lineEdit_53Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_53Window2, 9, 5, 1, 1)
        
        self.lineEdit_54Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_54Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_54Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_54Window2.setObjectName("lineEdit_54Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_54Window2, 11, 5, 1, 1)
        
        self.lineEdit_55Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_55Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_55Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_55Window2.setObjectName("lineEdit_55Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_55Window2, 13, 5, 1, 1)
        
        self.lineEdit_56Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_56Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_56Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_56Window2.setObjectName("lineEdit_56Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_56Window2, 15, 5, 1, 1)
        
        self.lineEdit_57Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_57Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_57Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_57Window2.setObjectName("lineEdit_57Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_57Window2, 17, 5, 1, 1)
        
        self.lineEdit_58Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_58Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_58Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_58Window2.setObjectName("lineEdit_58Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_58Window2, 19, 5, 1, 1)
        
        self.lineEdit_59Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_59Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_59Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_59Window2.setObjectName("lineEdit_59Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_59Window2, 21, 5, 1, 1)
        
        self.lineEdit_60Window2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_60Window2.sizePolicy().hasHeightForWidth())
        self.lineEdit_60Window2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lineEdit_60Window2.setObjectName("lineEdit_60Window2")
        self.gridLayoutWindow2.addWidget(self.lineEdit_60Window2, 23, 5, 1, 1)
        
        
        
        self.gridLayout_2.addLayout(self.gridLayoutWindow2, 1, 0, 1, 5)
        MainWindow.setCentralWidget(self.centralwidget)
        
        # Collectors of each widget
        self.lineEdit_col = MainWindow.findChildren(QtWidgets.QLineEdit)
        self.label_col = MainWindow.findChildren(QtWidgets.QLabel)
        
        # Removing the Fasit and Pages labels from the label collector
        del self.label_col[-2:]
        

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
   
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.updateButtonWindow2.setText(_translate("MainWindow", "Neste"))
        
        self.backButton.setText(_translate("MainWindow", "Tilbake"))
        
        self.fasitLabelWindow2.setText(_translate("MainWindow", "Fasit kode"))
#        self.labelPagesDone.setText(_translate("MainWindow", "Antall sider: {} av {}".format(self.current_page, self.max_pages)))
        